// Deployed contract addresses and network configuration
// Auto-generated by scripts/deploy-local-complete.sh on Mon  1 Dec 2025 14:28:41 GMT

export const CONTRACTS = {
  REGISTRY_ID: "CAKK4O5EQSVKUW2OW5XQYMAVS4TU7VGQJWWAK2ADV65OI2DIAV2JYBKP",
  SBT_ID: "CAZVWMBJCACO4K5L4JWK7GA7UHCQDSNN3PO6LVKYNFBLFVMYHLDUIF62",
  TREE_ID: "CC5E2WNM5GIY34JVW667Y7QHPN4B6SWD2ZMMWHQOFOFRHSHDMD6NMW6H",
  VOTING_ID: "CCLPDGSNSZDRVKLEJ5QM3U2AVQIROSXNJVYNWNL4PIKUX4TJYILQBVJB",
  COMMENTS_ID: "CD73UXTBUQQ4CIGGSLVUSORJUD2MKHLGJLX4JDBABVKAICCNOIVOXC3C",
} as const;

export const NETWORK_CONFIG = {
  rpcUrl: "https://rpc-futurenet.stellar.org",
  networkPassphrase: "Test SDF Future Network ; October 2022",
  networkName: "futurenet-local",
} as const;

// Contract method names for type safety
export const CONTRACT_METHODS = {
  REGISTRY: {
    CREATE_DAO: "create_dao",
    GET_DAO: "get_dao",
    CREATE_AND_INIT_DAO: "create_and_init_dao",
    CREATE_AND_INIT_DAO_NO_REG: "create_and_init_dao_no_reg",
  },
  SBT: {
    MINT: "mint",
    MINT_FROM_REGISTRY: "mint_from_registry",
    HAS: "has",
  },
  TREE: {
    INIT_TREE: "init_tree",
    REGISTER_WITH_CALLER: "register_with_caller",
    GET_ROOT: "get_root",
  },
  VOTING: {
    SET_VK: "set_vk",
    CREATE_PROPOSAL: "create_proposal",
    VOTE: "vote",
    GET_PROPOSAL: "get_proposal",
    GET_RESULTS: "get_results",
  },
} as const;
