// Deployed contract addresses and network configuration
// Auto-generated by scripts/deploy-local-complete.sh on Sun 23 Nov 2025 22:33:13 GMT

export const CONTRACTS = {
  REGISTRY_ID: "CBUOISGNHQQFXFJJLYMQDEMEBPFKXWRXDFQGJTYNEYRG6N4MBUVY6O3C",
  SBT_ID: "CAYSTVBYTQWJRLSONUO3Z25GLT4F6V4XAFQECWX44CANTPA6B7OIKAM2",
  TREE_ID: "CCT6MUCZLDBXZNJX2VKR5GVAYPPZEJF26KSCHUT22FOP7XLWZQQE7J2G",
  VOTING_ID: "CBOSMQ2DH4H4VKLZJEPWXTBDODEO4O7QPUJQGHBEKSENRARWCABDQCV2",
} as const;

export const NETWORK_CONFIG = {
  rpcUrl: "http://localhost:8000/soroban/rpc",
  networkPassphrase: "Test SDF Future Network ; October 2022",
  networkName: "futurenet-local",
} as const;

// Contract method names for type safety
export const CONTRACT_METHODS = {
  REGISTRY: {
    CREATE_DAO: "create_dao",
    GET_DAO: "get_dao",
    CREATE_AND_INIT_DAO: "create_and_init_dao",
    CREATE_AND_INIT_DAO_NO_REG: "create_and_init_dao_no_reg",
  },
  SBT: {
    MINT: "mint",
    MINT_FROM_REGISTRY: "mint_from_registry",
    HAS: "has",
  },
  TREE: {
    INIT_TREE: "init_tree",
    REGISTER_WITH_CALLER: "register_with_caller",
    GET_ROOT: "get_root",
  },
  VOTING: {
    SET_VK: "set_vk",
    CREATE_PROPOSAL: "create_proposal",
    VOTE: "vote",
    GET_PROPOSAL: "get_proposal",
    GET_RESULTS: "get_results",
  },
} as const;
