// Deployed contract addresses and network configuration
// Auto-generated by scripts/deploy-local-complete.sh on Fri 28 Nov 2025 20:26:27 GMT

export const CONTRACTS = {
  REGISTRY_ID: "CDCR6HA6NKVVQ4P4TVOPC6O3TQCAAQJPWNDWTPITL3FKWORY6HFKBQZZ",
  SBT_ID: "CCKOLOJDPTONWTT4ISOA7NAG7P62IXWSMVIXOC4X2KG6XFWATTHC5FYZ",
  TREE_ID: "CDQYMXQDZYQN2SATE65FRDX4JEIZJKHVFTMZ56JNTYJQUKVXU5A5FQIN",
  VOTING_ID: "CBSJT3XYBRBBDVTIMV6PHAWVNRNRJTHU5NKBPIEQDW4CCSEPDOAL755K",
  COMMENTS_ID: "CCXJQJR2W7QJS7TDBCQKJBKT54DRSVNDH65PMQ2VGS734K6QSSYPYEXE",
} as const;

export const NETWORK_CONFIG = {
  rpcUrl: "https://rpc-futurenet.stellar.org",
  networkPassphrase: "Test SDF Future Network ; October 2022",
  networkName: "futurenet-local",
} as const;

// Contract method names for type safety
export const CONTRACT_METHODS = {
  REGISTRY: {
    CREATE_DAO: "create_dao",
    GET_DAO: "get_dao",
    CREATE_AND_INIT_DAO: "create_and_init_dao",
    CREATE_AND_INIT_DAO_NO_REG: "create_and_init_dao_no_reg",
  },
  SBT: {
    MINT: "mint",
    MINT_FROM_REGISTRY: "mint_from_registry",
    HAS: "has",
  },
  TREE: {
    INIT_TREE: "init_tree",
    REGISTER_WITH_CALLER: "register_with_caller",
    GET_ROOT: "get_root",
  },
  VOTING: {
    SET_VK: "set_vk",
    CREATE_PROPOSAL: "create_proposal",
    VOTE: "vote",
    GET_PROPOSAL: "get_proposal",
    GET_RESULTS: "get_results",
  },
} as const;
