#!/bin/bash
set -e

echo "=== Complete DaoVote Deployment Script ==="
echo "This script will:"
echo "1. Build all contracts"
echo "2. Deploy all contracts to local futurenet"
echo "3. Generate TypeScript bindings"
echo "4. Update frontend configuration"
echo ""

# Configuration
KEY_NAME="${KEY_NAME:-mykey}"
RPC_URL="${RPC_URL:-http://localhost:8000/soroban/rpc}"
NETWORK_PASSPHRASE="${NETWORK_PASSPHRASE:-Test SDF Future Network ; October 2022}"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

step() {
  echo -e "${BLUE}==>${NC} $1"
}

success() {
  echo -e "${GREEN}✓${NC} $1"
}

warn() {
  echo -e "${YELLOW}⚠${NC} $1"
}

# Step 1: Build contracts
step "Building all contracts..."
cargo build --target wasm32v1-none --release
success "Contracts built successfully"

# Step 2: Deploy contracts
step "Deploying contracts to local futurenet..."

# Deploy DAO Registry
echo "Deploying DAO Registry..."
REGISTRY_ID=$(stellar contract deploy \
  --wasm target/wasm32v1-none/release/dao_registry.wasm \
  --source $KEY_NAME \
  --rpc-url "$RPC_URL" \
  --network-passphrase "$NETWORK_PASSPHRASE" 2>&1 | tail -1)
success "DAO Registry deployed: $REGISTRY_ID"

# Deploy Membership SBT
echo "Deploying Membership SBT..."
SBT_ID=$(stellar contract deploy \
  --wasm target/wasm32v1-none/release/membership_sbt.wasm \
  --source $KEY_NAME \
  --rpc-url "$RPC_URL" \
  --network-passphrase "$NETWORK_PASSPHRASE" \
  -- \
  --registry "$REGISTRY_ID" 2>&1 | grep -E '^C[A-Z0-9]{55}$' | tail -1)
success "Membership SBT deployed: $SBT_ID"

# Deploy Membership Tree
echo "Deploying Membership Tree..."
TREE_ID=$(stellar contract deploy \
  --wasm target/wasm32v1-none/release/membership_tree.wasm \
  --source $KEY_NAME \
  --rpc-url "$RPC_URL" \
  --network-passphrase "$NETWORK_PASSPHRASE" \
  -- \
  --sbt_contract "$SBT_ID" 2>&1 | grep -E '^C[A-Z0-9]{55}$' | tail -1)
success "Membership Tree deployed: $TREE_ID"

# Deploy Voting
echo "Deploying Voting..."
VOTING_ID=$(stellar contract deploy \
  --wasm target/wasm32v1-none/release/voting.wasm \
  --source $KEY_NAME \
  --rpc-url "$RPC_URL" \
  --network-passphrase "$NETWORK_PASSPHRASE" \
  -- \
  --tree_contract "$TREE_ID" 2>&1 | grep -E '^C[A-Z0-9]{55}$' | tail -1)
success "Voting deployed: $VOTING_ID"

# Verify all contracts deployed
if [ -z "$TREE_ID" ] || [ -z "$VOTING_ID" ]; then
  warn "Failed to deploy all contracts. Retrying problematic deployments..."

  if [ -z "$TREE_ID" ]; then
    echo "Retrying Membership Tree deployment..."
    TREE_ID=$(stellar contract deploy \
      --wasm target/wasm32v1-none/release/membership_tree.wasm \
      --source $KEY_NAME \
      --rpc-url "$RPC_URL" \
      --network-passphrase "$NETWORK_PASSPHRASE" \
      -- \
      --sbt_contract "$SBT_ID" 2>&1 | grep '^C' | grep -v 'ℹ️' | tail -1)
  fi

  if [ -z "$VOTING_ID" ]; then
    echo "Retrying Voting deployment..."
    VOTING_ID=$(stellar contract deploy \
      --wasm target/wasm32v1-none/release/voting.wasm \
      --source $KEY_NAME \
      --rpc-url "$RPC_URL" \
      --network-passphrase "$NETWORK_PASSPHRASE" \
      -- \
      --tree_contract "$TREE_ID" 2>&1 | grep '^C' | grep -v 'ℹ️' | tail -1)
  fi
fi

# Step 3: Generate TypeScript bindings
step "Generating TypeScript bindings..."
rm -rf frontend/src/contracts
mkdir -p frontend/src/contracts

echo "Generating DAO Registry bindings..."
stellar contract bindings typescript \
  --contract-id "$REGISTRY_ID" \
  --rpc-url "$RPC_URL" \
  --network-passphrase "$NETWORK_PASSPHRASE" \
  --output-dir frontend/src/contracts/dao-registry \
  --overwrite
success "DAO Registry bindings generated"

echo "Generating Membership SBT bindings..."
stellar contract bindings typescript \
  --contract-id "$SBT_ID" \
  --rpc-url "$RPC_URL" \
  --network-passphrase "$NETWORK_PASSPHRASE" \
  --output-dir frontend/src/contracts/membership-sbt \
  --overwrite
success "Membership SBT bindings generated"

echo "Generating Membership Tree bindings..."
stellar contract bindings typescript \
  --contract-id "$TREE_ID" \
  --rpc-url "$RPC_URL" \
  --network-passphrase "$NETWORK_PASSPHRASE" \
  --output-dir frontend/src/contracts/membership-tree \
  --overwrite
success "Membership Tree bindings generated"

echo "Generating Voting bindings..."
stellar contract bindings typescript \
  --contract-id "$VOTING_ID" \
  --rpc-url "$RPC_URL" \
  --network-passphrase "$NETWORK_PASSPHRASE" \
  --output-dir frontend/src/contracts/voting \
  --overwrite
success "Voting bindings generated"

# Step 4: Update frontend configuration
step "Updating frontend configuration..."
cat > frontend/src/config/contracts.ts << EOF
// Deployed contract addresses and network configuration
// Auto-generated by scripts/deploy-local-complete.sh on $(date)

export const CONTRACTS = {
  REGISTRY_ID: "$REGISTRY_ID",
  SBT_ID: "$SBT_ID",
  TREE_ID: "$TREE_ID",
  VOTING_ID: "$VOTING_ID",
} as const;

export const NETWORK_CONFIG = {
  rpcUrl: "$RPC_URL",
  networkPassphrase: "$NETWORK_PASSPHRASE",
  networkName: "futurenet-local",
} as const;

// Contract method names for type safety
export const CONTRACT_METHODS = {
  REGISTRY: {
    CREATE_DAO: "create_dao",
    GET_DAO: "get_dao",
    CREATE_AND_INIT_DAO: "create_and_init_dao",
    CREATE_AND_INIT_DAO_NO_REG: "create_and_init_dao_no_reg",
  },
  SBT: {
    MINT: "mint",
    MINT_FROM_REGISTRY: "mint_from_registry",
    HAS: "has",
  },
  TREE: {
    INIT_TREE: "init_tree",
    REGISTER_WITH_CALLER: "register_with_caller",
    GET_ROOT: "get_root",
  },
  VOTING: {
    SET_VK: "set_vk",
    CREATE_PROPOSAL: "create_proposal",
    VOTE: "vote",
    GET_PROPOSAL: "get_proposal",
    GET_RESULTS: "get_results",
  },
} as const;
EOF
success "Frontend configuration updated"

# Step 5: Update backend .env file
step "Updating backend configuration..."
cat > backend/.env << EOF
# DaoVote Relayer Configuration
# Auto-generated by scripts/deploy-local-complete.sh on $(date)

# Network Configuration
SOROBAN_RPC_URL=$RPC_URL
NETWORK_PASSPHRASE=$NETWORK_PASSPHRASE

# Relayer Account
RELAYER_SECRET_KEY=SCRQUW53C3DE664SG7DOTHZI5NDKYIGDOWMI7QGUCOKQM77NAYO25ER5

# Contract Addresses
VOTING_CONTRACT_ID=$VOTING_ID
TREE_CONTRACT_ID=$TREE_ID

# Server Configuration
PORT=3001

# CORS Configuration
CORS_ORIGIN=http://localhost:5173
EOF
success "Backend configuration updated"

# Summary
echo ""
echo -e "${GREEN}=== Deployment Complete! ===${NC}"
echo ""
echo "Contract Addresses:"
echo "  DAO Registry:    $REGISTRY_ID"
echo "  Membership SBT:  $SBT_ID"
echo "  Membership Tree: $TREE_ID"
echo "  Voting:          $VOTING_ID"
echo ""
echo "Next steps:"
echo "  1. Start the relayer: cd backend && npm run relayer"
echo "  2. Start the frontend: cd frontend && npm run dev"
echo ""
