#!/bin/bash
# Comprehensive DaoVote deployment script
# Builds, deploys, and configures all contracts with proper dependency order

set -e

echo "=== DaoVote Comprehensive Deployment ==="

# Configuration
NETWORK="${NETWORK:-futurenet-local}"
KEY_NAME="${KEY_NAME:-mykey}"
RPC_URL="${RPC_URL:-http://localhost:8000/soroban/rpc}"
NETWORK_PASSPHRASE="${NETWORK_PASSPHRASE:-Test SDF Future Network ; October 2022}"
WASM_DIR="target/wasm32v1-none/release"

echo "Network: $NETWORK"
echo "Source Key: $KEY_NAME"
echo "RPC URL: $RPC_URL"
echo "Network Passphrase: $NETWORK_PASSPHRASE"
echo ""

# Step 1: Build contracts
echo "Step 1: Building contracts..."
cargo build --target wasm32v1-none --release
echo "  ✓ Contracts built"
echo ""

# Step 2: Deploy contracts in dependency order
echo "Step 2: Deploying contracts..."

echo "  2.1. Deploying DAO Registry (no constructor)..."
REGISTRY_ID=$(stellar contract deploy \
    --wasm "$WASM_DIR/dao_registry.wasm" \
    --source "$KEY_NAME" \
    --rpc-url "$RPC_URL" \
    --network-passphrase "$NETWORK_PASSPHRASE" 2>&1 | tail -1)
echo "      ✓ Registry: $REGISTRY_ID"

echo "  2.2. Deploying Membership SBT (constructor: registry)..."
SBT_ID=$(stellar contract deploy \
    --wasm "$WASM_DIR/membership_sbt.wasm" \
    --source "$KEY_NAME" \
    --rpc-url "$RPC_URL" \
    --network-passphrase "$NETWORK_PASSPHRASE" \
    -- --registry "$REGISTRY_ID" 2>&1 | tail -1)
echo "      ✓ SBT: $SBT_ID"

echo "  2.3. Deploying Membership Tree (constructor: sbt_contract)..."
TREE_ID=$(stellar contract deploy \
    --wasm "$WASM_DIR/membership_tree.wasm" \
    --source "$KEY_NAME" \
    --rpc-url "$RPC_URL" \
    --network-passphrase "$NETWORK_PASSPHRASE" \
    -- --sbt_contract "$SBT_ID" 2>&1 | tail -1)
echo "      ✓ Tree: $TREE_ID"

echo "  2.3a. Initializing zeros cache (precompute Poseidon zero values)..."
stellar contract invoke \
    --id "$TREE_ID" \
    --source "$KEY_NAME" \
    --rpc-url "$RPC_URL" \
    --network-passphrase "$NETWORK_PASSPHRASE" \
    -- init_zeros_cache > /dev/null 2>&1
echo "      ✓ Zeros cache initialized"

echo "  2.4. Deploying Voting (constructor: tree_contract)..."
VOTING_ID=$(stellar contract deploy \
    --wasm "$WASM_DIR/voting.wasm" \
    --source "$KEY_NAME" \
    --rpc-url "$RPC_URL" \
    --network-passphrase "$NETWORK_PASSPHRASE" \
    -- --tree_contract "$TREE_ID" 2>&1 | tail -1)
echo "      ✓ Voting: $VOTING_ID"
echo ""

# Step 3: Save configuration
echo "Step 3: Saving configuration..."

# Save shell config
cat > .deployed-contracts << EOF
# DaoVote Contract Addresses ($NETWORK)
# Deployed: $(date)

export REGISTRY_ID="$REGISTRY_ID"
export SBT_ID="$SBT_ID"
export TREE_ID="$TREE_ID"
export VOTING_ID="$VOTING_ID"

export KEY_NAME="$KEY_NAME"
export RPC_URL="$RPC_URL"
export NETWORK_PASSPHRASE="$NETWORK_PASSPHRASE"
export NETWORK="$NETWORK"

# Usage: source .deployed-contracts
EOF
echo "  ✓ Saved .deployed-contracts"

# Update backend .env with new contract addresses
echo "  ✓ Updating backend/.env with new contract addresses"
if [ -f backend/.env ]; then
  # Update existing .env file
  sed -i.bak "s/^VOTING_CONTRACT_ID=.*/VOTING_CONTRACT_ID=$VOTING_ID/" backend/.env
  sed -i.bak "s/^TREE_CONTRACT_ID=.*/TREE_CONTRACT_ID=$TREE_ID/" backend/.env
  rm -f backend/.env.bak
else
  echo "Warning: backend/.env not found, skipping backend config update"
fi

# Update frontend config
cat > frontend/src/config/contracts.ts << EOF
// Deployed contract addresses and network configuration
// Auto-generated by scripts/deploy.sh on $(date)

export const CONTRACTS = {
  REGISTRY_ID: "$REGISTRY_ID",
  SBT_ID: "$SBT_ID",
  TREE_ID: "$TREE_ID",
  VOTING_ID: "$VOTING_ID",
} as const;

export const NETWORK_CONFIG = {
  rpcUrl: "$RPC_URL",
  networkPassphrase: "$NETWORK_PASSPHRASE",
  networkName: "$NETWORK",
} as const;

// Contract method names for type safety
export const CONTRACT_METHODS = {
  REGISTRY: {
    CREATE_DAO: "create_dao",
    GET_DAO: "get_dao",
    CREATE_AND_INIT_DAO: "create_and_init_dao",
  },
  SBT: {
    MINT: "mint",
    MINT_FROM_REGISTRY: "mint_from_registry",
    HAS: "has",
  },
  TREE: {
    INIT_TREE: "init_tree",
    REGISTER_WITH_CALLER: "register_with_caller",
    GET_ROOT: "get_root",
  },
  VOTING: {
    SET_VK: "set_vk",
    CREATE_PROPOSAL: "create_proposal",
    VOTE: "vote",
    GET_PROPOSAL: "get_proposal",
    GET_RESULTS: "get_results",
  },
} as const;
EOF
echo "  ✓ Updated frontend/src/config/contracts.ts"
echo ""

# Step 4: Generate and build TypeScript bindings
echo "Step 4: Generating TypeScript bindings..."
stellar contract bindings typescript \
    --wasm "$WASM_DIR/dao_registry.wasm" \
    --output-dir frontend/src/contracts/dao-registry \
    --overwrite > /dev/null 2>&1
(cd frontend/src/contracts/dao-registry && npm install > /dev/null 2>&1 && npm run build > /dev/null 2>&1)
echo "  ✓ Generated and built dao-registry bindings"

stellar contract bindings typescript \
    --wasm "$WASM_DIR/membership_sbt.wasm" \
    --output-dir frontend/src/contracts/membership-sbt \
    --overwrite > /dev/null 2>&1
(cd frontend/src/contracts/membership-sbt && npm install > /dev/null 2>&1 && npm run build > /dev/null 2>&1)
echo "  ✓ Generated and built membership-sbt bindings"

stellar contract bindings typescript \
    --wasm "$WASM_DIR/membership_tree.wasm" \
    --output-dir frontend/src/contracts/membership-tree \
    --overwrite > /dev/null 2>&1
(cd frontend/src/contracts/membership-tree && npm install > /dev/null 2>&1 && npm run build > /dev/null 2>&1)
echo "  ✓ Generated and built membership-tree bindings"

stellar contract bindings typescript \
    --wasm "$WASM_DIR/voting.wasm" \
    --output-dir frontend/src/contracts/voting \
    --overwrite > /dev/null 2>&1
(cd frontend/src/contracts/voting && npm install > /dev/null 2>&1 && npm run build > /dev/null 2>&1)
echo "  ✓ Generated and built voting bindings"
echo ""

# Summary
echo "=== Deployment Complete ==="
echo ""
echo "Contract Addresses:"
echo "  Registry: $REGISTRY_ID"
echo "  SBT:      $SBT_ID"
echo "  Tree:     $TREE_ID"
echo "  Voting:   $VOTING_ID"
echo ""
echo "Configuration saved to:"
echo "  - .deployed-contracts (shell config)"
echo "  - frontend/src/config/contracts.ts (TypeScript config)"
echo ""
echo "TypeScript bindings generated in frontend/src/contracts/"
echo ""
echo "To use deployed contracts:"
echo "  source .deployed-contracts"
echo ""
